{ lib, writeText }:
{
  cells ? [ ],
}:

let
  emit =
    cell:
    let
      commentLine = if cell ? comment then "    // ${cell.comment}\n" else "";
    in
    ''
      ${commentLine}    (* keep *)
          ${cell.module} ${cell.instance} ();
    '';

  body = ''
    // SPDX-FileCopyrightText: (C) 2026 Midstall Inc.
    // SPDX-License-Identifier: Apache-2.0
    //
    // GENERATED by pkgs/aegis-tapeout-lr/lib/mk-fab-required-cells.nix.
    // Do not edit; regenerate by rebuilding the tapeout-lr derivation.
    //
    // This file is `\`included inside the chip_top module body, so each
    // entry below is a module-scope instantiation, not a separate
    // module declaration.

  ''
  + lib.concatMapStrings emit cells;
in
writeText "fab_required_cells.svh" body
