{ lib, writeText }:
{ pdk }:

let
  c = pdk.librelane.padCells;
  body = ''
    // SPDX-FileCopyrightText: (C) 2026 Midstall Inc.
    // SPDX-License-Identifier: Apache-2.0
    //
    // GENERATED by pkgs/aegis-tapeout-lr/lib/mk-pad-defines.nix from
    // pdk.librelane.padCells. Do not edit; regenerate by rebuilding
    // the tapeout-lr derivation.

    `ifndef AEGIS_PAD_DEFINES_SVH
    `define AEGIS_PAD_DEFINES_SVH

    `define BIDIR_PAD_CELL         ${c.bidirCell}
    `define INPUT_CMOS_PAD_CELL    ${c.inputCmosCell}
    `define INPUT_SCHMITT_PAD_CELL ${c.inputSchmittCell}
    `define ANALOG_PAD_CELL        ${c.analogCell}
    `define POWER_PAD_CELL         ${c.powerPadCell}
    `define GROUND_PAD_CELL        ${c.groundPadCell}

    `endif // AEGIS_PAD_DEFINES_SVH
  '';
in
writeText "pad_defines.svh" body
